### PR TITLE
Build with `-Wunused`, `-Wall` and `-Werror`

### PR DESCRIPTION
**Pull request by schu**
Also, fix what looks like a typo in the `is_ipv4_mapped_ipv6` branch of
`kretprobe__tcp_v6_connect`.

### CODE REVIEW

**Comment by schu** [comment]
@alban @iaguis please take a look. I'm not sure about the typo (i.e. is `&t4` correct here?) and if we should keep a comment regarding `IPPROTO_TCP`.

**Comment by alban** [comment]
This looks correct to me. Does it work on a 4.4 kernel?

**Comment by schu** [comment]
> Does it work on a 4.4 kernel?

We run the tests on 4.4.45.

**Comment by alban** [comment]
LGTM

**Comment by alban** [comment]
This needs to be rebased & recompiled to resolve the conflict.

**Comment by schu** [comment]
Rebased.

**Pull request merged**
