### PR TITLE
tracer: close channels on Stop()

### PR DESCRIPTION
**Pull request by alban**
PerfMap's PollStop() documentation says the channel should be closed
after calling PollStop():
https://github.com/iovisor/gobpf/blob/d0a3e1b/elf/perf.go#L241-L242

This is solving a leaking go routine issue in Scope:
https://github.com/weaveworks/scope/pull/2735#issuecomment-320988997

-----

/cc @iaguis @2opremio @schu

### CODE REVIEW

**Comment by rade** [comment]
btw `PollStop` is rather non-idiomatic - the typical way to do this kind of signalling is to `close()` a channel of type `struct{}`.

**Comment by alban** [comment]
@rade ok, I filed https://github.com/iovisor/gobpf/issues/69 for this.

**Comment by 2opremio** [comment]
I agree with @rade . I think it's worth fixing it now, but I am fine with fixing it later if you prefer.

**Comment by alban** [comment]
idiomatic close in gobpf PR https://github.com/iovisor/gobpf/pull/70

I'll update this PR shortly.

**Comment by alban** [comment]
I updated the gobpf vendoring. I needed to change the `select{}` to avoid a panic ("panic: runtime error: index out of range"), see comment in the code.

It was working fine for a while but now I got another panic:
```
panic: send on closed channel

goroutine 75 [running]:
github.com/weaveworks/scope/vendor/github.com/weaveworks/tcptracer-bpf/vendor/github.com/iovisor/gobpf/elf.(*PerfMap).PollStart.func1(0xc420270370, 0xc422eff000, 0xc422eedfe0)
	/go/src/github.com/weaveworks/scope/vendor/github.com/weaveworks/tcptracer-bpf/vendor/github.com/iovisor/gobpf/elf/perf.go:229 +0x4f7
created by github.com/weaveworks/scope/vendor/github.com/weaveworks/tcptracer-bpf/vendor/github.com/iovisor/gobpf/elf.(*PerfMap).PollStart
	/go/src/github.com/weaveworks/scope/vendor/github.com/weaveworks/tcptracer-bpf/vendor/github.com/iovisor/gobpf/elf/perf.go:238 +0xf1
```

I am checking this...

**Comment by alban** [comment]
[channel closing principle](http://www.tapirgames.com/blog/golang-channel-closing):

> One general principle of using Go channels is don't close a channel from the receiver side

This PR should be rethought..

**Comment by rade** [comment]
@alban you beat me to quoting that :)

**Comment by alban** [comment]
Waiting for https://github.com/iovisor/gobpf/pull/71

**Comment by alban** [comment]
Closing in favor of https://github.com/weaveworks/tcptracer-bpf/pull/50

**Pull request closed without merging**
