### PR TITLE
bump gobpf version

### PR DESCRIPTION
**Pull request by rade**
This is needed to get ARM builds to work. See [Weave Scope CI failure](https://circleci.com/gh/weaveworks/scope/7667)

### CODE REVIEW

**Comment by rade** [comment]
bah, failure in CI. Here's what happens when I run the tests locally...
```
matthias@xps:~/go/src/github.com/weaveworks/tcptracer-bpf/tests$ sudo ./run 
4.10.0-26-generic
action: connect pid: 15855 saddr: 127.0.0.1:56202 daddr: 127.0.0.1:61112
action: connect pid: 15854 saddr: 127.0.0.1:48694 daddr: 127.0.0.1:61111
action: fdinstall pid: 14625 fd: 5
action: accept pid: 15853 saddr: 127.0.0.1:61111 daddr: 127.0.0.1:48694
action: close pid: 15855 saddr: 127.0.0.1:56202 daddr: 127.0.0.1:61112
action: close pid: 14625 saddr: 127.0.0.1:61112 daddr: 127.0.0.1:56202
./test.sh: line 21: 15853 Terminated              nsenter --net="${netns}" nc -l "${port}" < /dev/null
./test.sh: line 21: 15854 Terminated              nsenter --net="${netns}" nc 127.0.0.1 "${port}"
matthias@xps:~/go/src/github.com/weaveworks/tcptracer-bpf/tests$ echo $?
124
```
The problem here is that it's only getting 6 out of 8 events. The two missing ones are close events with `saddr: 127.0.0.1:61111` and `daddr: 127.0.0.1:61111`, respectively.

**Comment by rade** [comment]
> The problem here is that it's only getting 6 out of 8 events.

That's just due to `nc` weirdness; probably a version issue. When I add `-d` on the listening side and `-N` on the connecting side it works fine.

That's not the cause of the CI failure though. There the tracer doesn't appear to receive any events at all!

**Comment by rade** [comment]
So this time the semaphoreci test succeeded, unlike in the [first test run](https://semaphoreci.com/2opremio/tcptracer-bpf/branches/bump-gobpf-version/builds/1) of exactly the same version.

**Comment by 2opremio** [comment]
> So this time the semaphoreci test succeeded, unlike in the [first test run](https://semaphoreci.com/2opremio/tcptracer-bpf/branches/bump-gobpf-version/builds/1) of exactly the same version.

Odd .. I am totally new to semaphoreci myself, let's assume it was transient unless it happens again

**Review by 2opremio — APPROVED** [review]

**Pull request merged**
